config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  
  resources :posts do
    resources :comments, only: [:new, :create, :destroy, :edit, :update]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def edit
    @post        = Post.find(params[:post_id])
    @comment     = Comment.find(params[:id])
  end
  
  def update
    @comment      = Comment.find(params[:id])
    @post         = Post.find(params[:comment][:post_id])
    if @comment.update_attributes(comment_params)
      redirect_to post_path(@post), {notice: "編集が完了しました"}
    else
      redirect_to :back, notice: "編集に失敗しました"
    end 
  end

  # コメント作成
  def new
    @post            = Post.find(params[:post_id])
    @comment         = @post.comments.build
  end
  
  def create
    @comment      = Comment.new(comment_params)
    @post         = Post.find(params[:comment][:post_id])
    if @comment.save
      redirect_to post_path(@post), {notice: "投稿が完了しました"}
    else
      redirect_to :back, notice: "投稿に失敗しました"
    end 
  end
  
  private def comment_params
    params.require(:comment).permit(:name, :content, :post_id)
  end

  def destroy
    id = params[:id]
    Comment.find(id).destroy
    flash[:success] = "削除しました"
    redirect_to :back
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  # ブログ一覧表示
  def index
    @posts     = Post.all
  end

  def show
    id         = params[:id]
    @post      = Post.find(id)
    @comments  = @post.comments.all
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  # 記事作成
  def new
    @post      = Post.new
  end
  
  # routeにpostを追加する
  def create
    @post      = Post.new(post_params)
    if @post.save
      redirect_to root_path, notice: "投稿が完了しました"
    else
      render :new
    end 
  end
  
  def update
    @post      = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to root_path, notice: "投稿が完了しました"
    else
      redirect_to :back, notice: "編集に失敗しました"
    end 
  end
  
  # StrongParamater rails4から
  # paramが:postというキーを持ち，titleとcontentを持っている
  private def post_params
    params.require(:post).permit(:title, :content)
  end

  def destroy
    id          = params[:id]
    Post.find(id).destroy
    redirect_to root_path, notice: "削除しました" 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/delete.html.erb
<h1>Comments#delete</h1>
<p>Find me in app/views/comments/delete.html.erb</p>

app/views/comments/edit.html.erb
<h1>コメント編集</h1>

<%= form_for @comment, url: post_comment_path(@post, @comment) do |f| %>
  <%= f.label :name, "名前" %>
  <%= f.text_field :name %>
  
  <%= f.label :content, "内容" %>
  <%= f.text_field :content %>
  
  <%= f.hidden_field :post_id %>
  <%= f.submit "投稿する" %>
<% end %>

app/views/comments/new.html.erb
<h1>新規コメント</h1>

<%= form_for @comment, url: post_comments_path(@post) do |f| %>
  <%= f.label :name, "名前" %>
  <%= f.text_field :name %>
  
  <%= f.label :content, "内容" %>
  <%= f.text_field :content %>
  
  <%= f.hidden_field :post_id %>
  <%= f.submit "投稿する" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/delete.html.erb
<h1>Posts#delete</h1>
<p>Find me in app/views/posts/delete.html.erb</p>

app/views/posts/edit.html.erb
<h1>投稿編集</h1>

<%= form_for @post, url: post_path(@post) do |f| %>
  <%= f.label :title, "タイトル" %>
  <%= f.text_field :title %>
  
  <%= f.label :content, "記事" %>
  <%= f.text_field :content %>
  
  <%= f.submit "編集する" %>
<% end %>

app/views/posts/index.html.erb
<h1>課題1 簡単なブログ</h1>
<%= link_to("記事作成", :controller => "posts", :action => "new") %>
<ul>
<% @posts.each do |post| %>
  <li><%= link_to(post.title, :controller => "posts", :action => "show", :id => post.id) %>&nbsp;
  <%= link_to("編集", edit_post_path(post)) %>&nbsp;
  <%= link_to("削除", {:controller => "posts", :action => "destroy", :id => post.id}, data:{:confirm => post.title + "を削除します"} ) %></li>
<% end %>
</ul>

app/views/posts/new.html.erb
<h1>新規投稿</h1>

<%= form_for @post  do |f| %>
  <%= f.label :title, "タイトル" %>
  <%= f.text_field :title %>
  
  <%= f.label :content, "記事" %>
  <%= f.text_field :content %>
  
  <%= f.submit "投稿する" %>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<%= @post.content %>
<h2>コメント</h2>
<% @comments.each do |comment| %>
  <%= comment.name %><br>
  <%= comment.content %><br>
  <%= link_to("編集", edit_post_comment_path(@post, comment)) %><br>
  <%= link_to("削除", post_comment_path(@post, comment), method: :delete, data:{:confirm =>"コメントを削除します"} ) %><br>
<% end %>

<%= link_to("コメントを投稿する", new_post_comment_path(@post)) %><br>